misc: move to std::print
hyprwm/hyprlock pull request #592
Opened 2024-12-19 19:00 UTC by PaideiaDilemma

2024-12-21 14:54 UTC, vaxerski approved these changes

2024-12-21 14:54 UTC, vaxerski commented
conflict tho

2024-12-22 05:52 UTC, littleblack111 commented
wouldn't it be better if u replace cerr to print(stderr, ...)

2024-12-22 07:20 UTC, PaideiaDilemma commented
@littleblack111 
I think help should not be printed to stderr.
But I can change it back. Do not have a strong opinion on it.

2024-12-22 12:22 UTC, littleblack111 requested changes

2024-12-22 13:26 UTC, PaideiaDilemma commented on src/main.cpp
> -        std::cerr << "Error: Missing value for " << flag << " option.\n";
ups yeah thanks!

2024-12-22 14:56 UTC, littleblack111 approved these changes

2024-12-22 15:09 UTC, merged